@startuml
title Rilevamento intruso (Observer Pattern)

start
:Movimento fisico rilevato nell'ambiente;

if (Il **MotionSensor** è attivo?) then (No)
    :Ignora il movimento;
    stop
else (Sì)
    :Esegue **detectIntruder()**;
    :Chiama **notifyObservers("Intrusione Rilevata")**;

    note right: notifica a tutti gli iscritti

    fork
        ' Ramo dell'AlarmSystem
        :L'**AlarmSystem** riceve **update()**;
        :Imposta **isRinging = true**;
        :Attiva suono Sirena (Hardware);
    fork again
        ' Ramo della MobileApp
        :La **MobileApp** riceve **update()**;
        :Mostra **Notifica Push** all'utente;
        :Richiede il video alla **SmartCamera**\ntramite **getLiveFeed()**;
        :Visualizza il video sullo schermo;
    end fork

    :Fine gestione emergenza;
    stop
endif
@enduml