@startuml
autonumber
actor "Ladro" as Ladro

box "Subject (Observable)" #E8F8F5
participant "sensor : MotionSensor" as Sensor
end box

box "Observers (Iscritti)" #FEF9E7
participant "app : MobileApp" as App
participant "sirena : AlarmSystem" as Sirena
participant "logger : SystemLogger" as Logger
end box

Ladro -> Sensor : detectIntruder()
activate Sensor
note right of Sensor: Il sensore rileva il movimento\ne invia le notifiche

Sensor -> Sensor : notifyObservers("Intruso in salotto")
activate Sensor
note right of Sensor: Itera sulla sua lista interna\ndegli observers

== Broadcoast agli Observer ==

Sensor -> App : update("Intruso in Salotto")
activate App
note right of App: Mostra una notifica\npush sul telefono
App --> Sensor : return
deactivate App

Sensor -> Sirena : update("Intruso in salotto")
activate Sirena
note right of Sirena: Attiva l'allarme
Sirena --> Sensor : return
deactivate Sirena

Sensor -> Logger : update("Intruso in salotto")
activate Logger
note right of Logger: Registra l'evento\nnel database
Logger --> Sensor : return
deactivate Logger

deactivate Sensor
Sensor --> Ladro : (fine processo)
deactivate Sensor

@enduml