@startuml
autonumber
actor Client

box "Root Composite" #E8F8F5
participant "myHouse : House" as House
end box

box "Intermediate Composite" #FEF9E7
participant "livingRoom : Room" as Room
end box

box "Leaves (Dispositivi Base)" #F5EEF8
participant "roomThermostat : Thermostat" as Thermostat
participant "kitchenLight : LightBulb" as Light
end box

Client -> House : getConsumption()
activate House
note right of House: Itera sulla lista delle 'areas'

== Interazione con un Nodo Composto (Room) ==
House -> Room : getConsumption()
activate Room
note right of Room: Itera sulla sua lista 'devices'

Room -> Thermostat : getConsumption()
activate Thermostat
note right of Thermostat: La foglia calcola il suo\nconsumo base
Thermostat --> Room : return
deactivate Thermostat

note right of Room: Somma i consumi dei suoi 'devices'
Room --> House : return
deactivate Room

== Interazione con una Foglia Diretta (LightBulb) ==
House -> Light : getConsumption()
activate Light
note right of Light: La foglia calcola il suo\nconsumo base
Light --> House : return
deactivate Light

note right of House: Somma i consumi di tutte le sue 'areas'\n(Room + LightBulb)
House --> Client : return
deactivate House

@enduml