@startuml
autonumber
skinparam sequenceMessageAlign center

actor "Intruso" as Intruso
participant "sensore: MotionSensor" as Sensore
participant "sirena: AlarmSystem" as Sirena
participant "app: MobileApp" as App
participant "cam: SmartCamera" as Cam

Intruso -> Sensore : Movimento fisico
activate Sensore

Sensore -> Sensore : detectIntruder()
activate Sensore

Sensore -> Sensore : notifyObservers("Intrusione Rilevata")
activate Sensore

note over Sensore, App : Iterazione sulla lista observers
loop per ogni observer in observers

    Sensore -> Sirena : update("Intrusione rilevata")
    activate Sirena
    note right of Sirena : Suona l'allarme
    Sirena --> Sensore : void
    deactivate Sirena

    Sensore -> App : update("Intrusione Rilevata")
    activate App
    note right of App : Mostra notifica push

    App -> Cam : getLiveFeed()
    activate Cam
    Cam --> App : "[REC] Live Feed..."
    deactivate Cam

    App --> Sensore : void
    deactivate App
end

deactivate Sensore
deactivate Sensore
deactivate Sensore

@enduml