@startuml
autonumber
actor "Client (Room)" as Client

box "Target Interface (SmartDevice)" #F5EEF8
participant "adapter : BoseAdapter" as Adapter
end box

box "Adaptee (old device)" #EBF5FB
participant "bose : BoseSoundSystem" as Bose
end box

== Attivazione ==

Client -> Adapter : activate()
activate Adapter
note right of Adapter: Riceve il comando generico 'activate()' e lo traduce

Adapter -> Bose : playMusic()
activate Bose
note right of Bose: Il sistema audio inizia a suonare
Bose --> Adapter : return
deactivate Bose

Adapter --> Client : return
deactivate Adapter

== Disattivazione ==

Client -> Adapter : deactivate()
activate Adapter
note right of Adapter: Riceve il comando generico 'deactivate()' e lo traduce

Adapter -> Bose : stopMusic()
activate Bose
note right of Bose: Il sistema audio si ferma
Bose --> Adapter : return
deactivate Bose

Adapter --> Client : return
deactivate Adapter

== Lettura Consumi ==

Client -> Adapter : getConsumption()
activate Adapter

Adapter --> Client : return
deactivate Adapter

@enduml